# Generated by Django 5.2.3 on 2026-03-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_purchase_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='visitor',
        ),
    ]
