# Generated by Django 5.2.3 on 2026-03-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_purchase_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='visitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.visitor'),
            preserve_default=False,
        ),
    ]
