# Generated by Django 5.2.3 on 2026-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('crowd_percentage', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
