# Generated by Django 5.2.3 on 2026-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_crowddetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowddetection',
            name='people_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
