# Generated by Django 5.2.3 on 2026-03-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_xyz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XYZ',
        ),
    ]
