# Generated by Django 5.2.3 on 2026-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_xyz'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
