# Generated by Django 5.2.3 on 2026-03-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shopkeeper_latitude_shopkeeper_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='longitude',
        ),
    ]
