# Generated by Django 5.2.3 on 2026-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_shopkeeper_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
