# Generated by Django 5.2.3 on 2026-03-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_visitor_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='location',
            new_name='address',
        ),
    ]
