# Generated by Django 5.2.3 on 2026-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_location_visitor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
